# Define classes based on tree names in dataset file
classes:
    - other
    - rho
    - pi
    - a1

# Define list of variables to be used for training
# in the right order
variables:
    - Egamma1_tau
    - Egamma2_tau
    - Egamma3_tau
    - Epi_tau
    - rho_dEta_tau
    - rho_dphi_tau
    - gammas_dEta_tau
    - gammas_dR_tau
    - DeltaR2WRTtau_tau
    - eta
    - pt
    - Epi0
    - Epi
    - rho_dEta
    - rho_dphi
    - gammas_dEta
    - tau_decay_mode
    - Mrho
    - Mpi0
    - DeltaR2WRTtau
    - Mpi0_TwoHighGammas
    - Mpi0_ThreeHighGammas
    - Mpi0_FourHighGammas
    - Mrho_OneHighGammas
    - Mrho_TwoHighGammas
    - Mrho_ThreeHighGammas
    - Mrho_subleadingGamma

